services:
  bot:
    build: .
    container_name: telegram-bot
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongo:27017/telegram-bot?authSource=admin
      - BOT_TOKEN=8353947037:AAEo1r4t9xEbap_Z5w9P1okIFDxcCOYUzUA
      - ADMIN=6076223538
      - photoId=AgACAgIAAxkBAAMEaNaXX1rRiXOd59k9cDc96XVdc80AAm_3MRsaPrFKbrqbY_sXe9EBAAMCAAN5AAM2BA
      - CHECK_PAYMENT=-1003097441586
      - CHANNEL_IDS=-1002229098897
      - UZCARD=5614681627371952
      - SMM_API_URL=https://smmya.com/api/v2/
      - SMM_API_KEY=308bae5dfb58417f0fb728962db66b7a
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network